"""emailextract -- deterministic .eml/.msg email extraction (Phase 0: contracts + skeleton walker).

Turn 0.1 froze the contracts; Turn 0.2 added the container interface and the skeleton
walker (``emailextract.walk``). Importable with neither sibling repository installed and
without olefile -- this package depends only on docextract-core. Nothing here claims a
status for a file it has not read: what the walker does not build is recorded as
``unknown("not_built_in_phase0")``, never as an absence.
"""

from __future__ import annotations

from .model import (
    AttachmentOccurrence,
    BodyView,
    ChildLink,
    ChildLinkState,
    Classification,
    ClassificationClaim,
    ContainerFacts,
    ContainerKind,
    ContentFingerprint,
    CryptoKind,
    DecodeChain,
    DecorativeHint,
    DecorativeHintState,
    EmailDocument,
    EncodingSource,
    FlagHit,
    FlagRollup,
    FlagSection,
    GroupCount,
    HeaderField,
    HitLocation,
    MatchType,
    PartRecord,
    QuoteCrossCheck,
    REASON_TABLE,
    RollupScope,
    RunRecord,
    Selection,
    SameMessageCandidate,
    Status,
    StatusOutcome,
    ThreadEdge,
    ThreadSource,
    TriState,
    TriValue,
    TypeVerdicts,
    TypeVerdictSource,
    record_from_bytes,
    record_to_bytes,
)
from .timeevent import (
    Ambiguity,
    OffsetOrigin,
    Precision,
    Span,
    TimeEvent,
    TimeSource,
    TimeValue,
    Trust,
)
from .versions import (
    DECODE_CHAIN_VERSION,
    EMAIL_PARSER_VERSION,
    FLAG_SCHEMA_VERSION,
    HTMLTEXT_VERSION,
    HEADERTEXT_VERSION,
    OUTPUT_SCHEMA_VERSION,
    TEXTMODEL_VERSION,
    TIMEEVENT_VERSION,
)

__version__ = "0.1.0"


__all__ = [
    "Ambiguity",
    "AttachmentOccurrence",
    "BodyView",
    "ChildLink",
    "ChildLinkState",
    "Classification",
    "ClassificationClaim",
    "ContainerFacts",
    "ContainerKind",
    "ContentFingerprint",
    "CryptoKind",
    "DECODE_CHAIN_VERSION",
    "DecodeChain",
    "DecorativeHint",
    "DecorativeHintState",
    "EMAIL_PARSER_VERSION",
    "EmailDocument",
    "EncodingSource",
    "FLAG_SCHEMA_VERSION",
    "FlagHit",
    "FlagRollup",
    "FlagSection",
    "GroupCount",
    "HTMLTEXT_VERSION",
    "HEADERTEXT_VERSION",
    "HitLocation",
    "MatchType",
    "OUTPUT_SCHEMA_VERSION",
    "OffsetOrigin",
    "PartRecord",
    "Precision",
    "QuoteCrossCheck",
    "REASON_TABLE",
    "RollupScope",
    "RunRecord",
    "Selection",
    "SameMessageCandidate",
    "Span",
    "Status",
    "StatusOutcome",
    "TEXTMODEL_VERSION",
    "TIMEEVENT_VERSION",
    "ThreadEdge",
    "ThreadSource",
    "TimeEvent",
    "TimeSource",
    "TimeValue",
    "TriState",
    "TriValue",
    "Trust",
    "TypeVerdicts",
    "TypeVerdictSource",
    "record_from_bytes",
    "record_to_bytes",
]
