"""emailextract -- deterministic .eml/.msg email extraction (Phase 0: contracts + skeleton walker).

Turn 0.1 froze the contracts; Turn 0.2 added the container interface and the skeleton
walker (``emailextract.walk``). Importable with neither sibling repository installed and
without olefile -- this package depends only on docextract-core. Nothing here claims a
status for a file it has not read: what the walker does not build is recorded as
``unknown("not_built_in_phase0")``, never as an absence.
"""

from __future__ import annotations

from .model import (
    AttachmentOccurrence,
    BodyView,
    ChildLink,
    ChildLinkState,
    Classification,
    ClassificationClaim,
    ContainerFacts,
    ContainerKind,
    ContentFingerprint,
    CryptoKind,
    DecodeChain,
    DecorativeHint,
    DecorativeHintState,
    EmailDocument,
    EncodingSource,
    FlagHit,
    FlagRollup,
    FlagSection,
    GroupCount,
    HeaderField,
    HitLocation,
    MatchType,
    PartRecord,
    QuoteBoundary,
    QuoteCrossCheck,
    REASON_TABLE,
    RollupScope,
    RunRecord,
    Selection,
    SameMessageCandidate,
    Status,
    StatusOutcome,
    ThreadEdge,
    ThreadSource,
    TriState,
    TriValue,
    TypeVerdicts,
    TypeVerdictSource,
    ViewLevel,
    record_from_bytes,
    record_to_bytes,
)
from .assemble import (
    PROJECTION_VERSION_NAMES,
    Unresolvable,
    assemble,
    document_key,
    identity_projection,
    limits_fingerprint,
    projection_versions,
    resolve_span,
    run_id,
)
from .ingest import (
    HIT,
    OUTCOMES,
    SKIP_REASONS,
    SKIPPED,
    WRITTEN,
    IngestManifest,
    ManifestRow,
    ingest_path,
    manifest_store,
    read_manifest,
)
from .store import (
    DocumentArtifact,
    document_artifact,
    document_store,
    read_document,
    reingest_document_is_noop,
    store_document,
)
from .siblings import (
    ChildCitation,
    ChildCitationChild,
    ChildCitationStamp,
    ChildCitationVia,
    ChildLinkResult,
    ChildResult,
    CitationChildState,
    Locator,
    SiblingDerivedFacts,
    SiblingStore,
    discovery,
    is_installed,
    link_child,
    link_occurrence,
    missing_siblings,
    not_installed,
)
from .timeevent import (
    Ambiguity,
    OffsetOrigin,
    Precision,
    Span,
    TimeEvent,
    TimeSource,
    TimeValue,
    Trust,
)
from .versions import (
    DECODE_CHAIN_VERSION,
    EMAIL_PARSER_VERSION,
    FLAG_SCHEMA_VERSION,
    HTMLTEXT_VERSION,
    HEADERTEXT_VERSION,
    OUTPUT_SCHEMA_VERSION,
    TEXTMODEL_VERSION,
    TIMEEVENT_VERSION,
)

__version__ = "0.1.0"


__all__ = [
    "Ambiguity",
    "AttachmentOccurrence",
    "BodyView",
    "ChildCitation",
    "ChildCitationChild",
    "ChildCitationStamp",
    "ChildCitationVia",
    "ChildLink",
    "ChildLinkResult",
    "ChildLinkState",
    "ChildResult",
    "CitationChildState",
    "Classification",
    "ClassificationClaim",
    "ContainerFacts",
    "ContainerKind",
    "ContentFingerprint",
    "CryptoKind",
    "DECODE_CHAIN_VERSION",
    "DecodeChain",
    "DecorativeHint",
    "DecorativeHintState",
    "DocumentArtifact",
    "EMAIL_PARSER_VERSION",
    "EmailDocument",
    "EncodingSource",
    "FLAG_SCHEMA_VERSION",
    "FlagHit",
    "FlagRollup",
    "FlagSection",
    "GroupCount",
    "HIT",
    "HTMLTEXT_VERSION",
    "HEADERTEXT_VERSION",
    "HitLocation",
    "IngestManifest",
    "Locator",
    "ManifestRow",
    "MatchType",
    "OUTCOMES",
    "OUTPUT_SCHEMA_VERSION",
    "OffsetOrigin",
    "PROJECTION_VERSION_NAMES",
    "PartRecord",
    "Precision",
    "QuoteBoundary",
    "QuoteCrossCheck",
    "REASON_TABLE",
    "RollupScope",
    "RunRecord",
    "SKIPPED",
    "SKIP_REASONS",
    "Selection",
    "SameMessageCandidate",
    "SiblingDerivedFacts",
    "SiblingStore",
    "Span",
    "Status",
    "StatusOutcome",
    "TEXTMODEL_VERSION",
    "TIMEEVENT_VERSION",
    "ThreadEdge",
    "ThreadSource",
    "TimeEvent",
    "TimeSource",
    "TimeValue",
    "TriState",
    "TriValue",
    "Trust",
    "TypeVerdicts",
    "TypeVerdictSource",
    "Unresolvable",
    "ViewLevel",
    "WRITTEN",
    "assemble",
    "discovery",
    "document_artifact",
    "document_key",
    "document_store",
    "identity_projection",
    "ingest_path",
    "is_installed",
    "limits_fingerprint",
    "link_child",
    "link_occurrence",
    "manifest_store",
    "missing_siblings",
    "not_installed",
    "projection_versions",
    "read_document",
    "read_manifest",
    "record_from_bytes",
    "record_to_bytes",
    "reingest_document_is_noop",
    "resolve_span",
    "run_id",
    "store_document",
]
